version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: realestate-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrong@Passw0rd
      - POSTGRES_DB=RealEstateDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - realestate-network

  api:
    build:
      context: ./RealEstateAPI
      dockerfile: Dockerfile
    container_name: realestate-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=RealEstateDB;Username=postgres;Password=YourStrong@Passw0rd
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    networks:
      - realestate-network

volumes:
  postgres_data:

networks:
  realestate-network:
    driver: bridge